# Generated by Django 4.1.2 on 2022-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_learning_url',
            field=models.CharField(default='/cms/learn', max_length=1024, verbose_name='デフォルトラーニングURL'),
        ),
    ]
