# Generated by Django 4.1.2 on 2022-11-10 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefield',
            name='read_aloud_lang',
            field=models.CharField(default='en-US', max_length=255, validators=[django.core.validators.RegexValidator('^[^=<>~!\\\\\\*\\+\\.\\?\\{\\}\\(\\)\\[\\]\\^\\$\\|\\/]+$', '使用できない文字が含まれています。'), django.core.validators.RegexValidator('^\\S', '空白文字で開始できません。'), django.core.validators.RegexValidator('\\S$', '空白文字で終了できません。')], verbose_name='読み上げ言語'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_work',
            field=models.BooleanField(default=False, verbose_name='カード種別'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='活動状態'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=0, verbose_name='活動状態'),
        ),
    ]
