# Generated by Django 4.1.2 on 2022-11-11 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_notefield_read_aloud_lang_alter_card_is_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='actual_review_interval',
        ),
        migrations.AlterField(
            model_name='notefield',
            name='read_aloud_lang',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.RegexValidator('(^$)|(^[a-z]{2}-[A-Z]{2}$)', '不正な言語コードです。')], verbose_name='読み上げ言語'),
        ),
    ]
