# Generated by Django 4.1.2 on 2022-11-11 14:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_card_actual_review_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='actual_review_interval',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3153600000)], verbose_name='実際復習間隔'),
        ),
    ]
