# Generated by Django 4.1.2 on 2022-11-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_card_actual_review_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ul_review_interval',
        ),
    ]
