# Generated by Django 4.1.2 on 2022-11-11 14:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_card_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='estimated_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60), validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)], verbose_name='予想所要時間'),
        ),
        migrations.AddField(
            model_name='card',
            name='ul_review_interval',
            field=models.DurationField(default=datetime.timedelta(days=36500), validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3153600000)], verbose_name='上限復習間隔'),
        ),
    ]
