# Generated by Django 4.1.2 on 2022-11-13 04:29

import cms.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_card_estimated_time_card_ul_review_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_project_default_template',
            field=models.BooleanField(default=False, verbose_name='プロジェクトのデフォルトテンプレートに指定'),
        ),
        migrations.AlterField(
            model_name='card',
            name='actual_review_interval',
            field=models.DurationField(default=datetime.timedelta(0), validators=[cms.validators.DurationRangeValidator(max_delta=datetime.timedelta(days=36500), min_delta=datetime.timedelta(0))], verbose_name='実際復習間隔'),
        ),
        migrations.AlterField(
            model_name='card',
            name='estimated_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60), validators=[cms.validators.DurationRangeValidator(max_delta=datetime.timedelta(days=1), min_delta=datetime.timedelta(0))], verbose_name='予想所要時間'),
        ),
        migrations.AlterField(
            model_name='card',
            name='ul_review_interval',
            field=models.DurationField(default=datetime.timedelta(days=36500), validators=[cms.validators.DurationRangeValidator(max_delta=datetime.timedelta(days=36500), min_delta=datetime.timedelta(0))], verbose_name='上限復習間隔'),
        ),
    ]
