# Generated by Django 4.1.2 on 2022-11-13 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_note_is_project_default_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='post_pone',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='延期日時'),
            preserve_default=False,
        ),
    ]
