# Generated by Django 4.1.2 on 2022-11-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_card_post_pone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='post_pone',
            new_name='postpone_to',
        ),
    ]
