# Generated by Django 4.1.2 on 2022-11-14 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_rename_post_pone_card_postpone_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='postpone_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 22, 56, 685404), verbose_name='延期日時'),
        ),
    ]
