# Generated by Django 4.1.2 on 2022-11-18 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_card_postpone_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_answer_cards', to='cms.notefield', verbose_name='解答フィールド'),
        ),
        migrations.AlterField(
            model_name='card',
            name='postpone_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 17, 20, 12, 769120), verbose_name='延期先日時'),
        ),
        migrations.AlterField(
            model_name='card',
            name='problem_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_problem_cards', to='cms.notefield', verbose_name='問題フィールド'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_cards', to='cms.notefield', verbose_name='解答フィールド')),
                ('problem_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_cards', to='cms.notefield', verbose_name='問題フィールド')),
            ],
        ),
    ]
