# Generated by Django 4.1.2 on 2022-11-18 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_card_answer_field_alter_card_postpone_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.test', verbose_name='テスト'),
        ),
        migrations.AlterField(
            model_name='card',
            name='postpone_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 17, 29, 3, 118549), verbose_name='延期先日時'),
        ),
    ]
