# Generated by Django 4.1.2 on 2022-11-18 09:14

import cms.validators
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0013_remove_card_answer_field_remove_card_note_and_more'),
    ]

    operations = [
        migrations.RenameModel('Card','TestRegistry'),
    ]
