# Generated by Django 4.1.2 on 2022-11-18 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_rename_card_to_testregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='cms.note', verbose_name='ノート'),
        ),
        migrations.RenameField('testregistry', 'dependency_cards', 'dependency_testregistry_set'),
        migrations.AlterField(
            model_name='test',
            name='answer_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_tests', to='cms.notefield', verbose_name='解答フィールド'),
        ),
        migrations.AlterField(
            model_name='test',
            name='problem_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_tests', to='cms.notefield', verbose_name='問題フィールド'),
        ),
        migrations.AlterField(
            model_name='testregistry',
            name='postpone_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 19, 7, 0, 651916), verbose_name='延期先日時'),
        ),
        migrations.AlterField(
            model_name='testregistry',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.test', verbose_name='テスト'),
        ),
    ]
