# Generated by Django 4.1.2 on 2022-11-18 10:23

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0015_alter_testregistry_dependency_cards_test_note_and_more'),
    ]

    operations = [
        migrations.RenameModel('Note', 'Card'),
        migrations.RenameModel('NoteField', 'CardField'),
    ]
