# Generated by Django 4.1.2 on 2022-11-19 01:32

import cms.validators
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0018_alter_fields_note_to_card'),
    ]

    operations = [
        migrations.RenameModel('TestRegistry', 'ReviewManagement'),
        migrations.RenameField('ReviewManagement', 'dependency_testregistry_set', 'dependency_rm_set'),
        migrations.AlterField(
            model_name='reviewmanagement',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_set', to='cms.test', verbose_name='テスト'),
        ),
    ]
