# Generated by Django 4.1.2 on 2022-11-19 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_rename_testregistry_to_reviewmanagiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmanagement',
            name='dependency_rm_set',
            field=models.ManyToManyField(blank=True, related_name='dependent_rm_set', to='cms.reviewmanagement', verbose_name='依存先復習管理'),
        ),
        migrations.AlterField(
            model_name='reviewmanagement',
            name='order_in_card',
            field=models.IntegerField(default=0, verbose_name='カード内順序'),
        ),
    ]
