# Generated by Django 4.1.2 on 2022-11-19 05:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_reviewmanagement_dependency_rm_set_and_more'),
    ]

    operations = [
        migrations.RenameModel('Test', 'QA'),
    ]
