# Generated by Django 4.1.2 on 2022-11-19 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_rename_test_to_qa'),
    ]

    operations = [
        migrations.RenameField('qa','problem_field', 'question_field'),
    ]
