# Generated by Django 4.1.2 on 2022-11-19 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_rename_problem_to_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='answer_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_for_a', to='cms.cardfield', verbose_name='解答フィールド'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_set', to='cms.card', verbose_name='カード'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_for_q', to='cms.cardfield', verbose_name='問題フィールド'),
        ),
    ]
