# Generated by Django 4.1.2 on 2022-11-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_rename_test_reviewmanagement_qa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmanagement',
            name='order_in_card',
        ),
    ]
