# Generated by Django 4.1.2 on 2022-11-24 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0025_remove_reviewmanagement_order_in_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='star',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.CreateModel(
            name='ProjectLearningManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_active', models.BooleanField('活動状態', default=True)),
                ('star', models.IntegerField(default=0, verbose_name='星')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.project', verbose_name='プロジェクト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
    ]
