# Generated by Django 4.1.2 on 2022-11-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_remove_project_star_remove_project_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmanagement',
            name='status',
        ),
        migrations.AddField(
            model_name='reviewmanagement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='活動状態'),
        ),
        migrations.AlterField(
            model_name='cardfield',
            name='read_aloud_lang',
            field=models.CharField(blank=True, default='', max_length=31, null=True, verbose_name='読み上げ言語コード'),
        ),
        migrations.AlterField(
            model_name='projectlearningmanagement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.project', verbose_name='プロジェクト'),
        ),
    ]
