# Generated by Django 4.1.2 on 2022-11-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_remove_reviewmanagement_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmanagement',
            old_name='is_work',
            new_name='need_session',
        ),
    ]
