# Generated by Django 4.1.2 on 2022-12-02 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0028_rename_is_work_to_need_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_project_default_template',
        ),
        migrations.AddField(
            model_name='project',
            name='default_template_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_for_pdt', to='cms.card', verbose_name='デフォルトテンプレートカード'),
        ),
    ]
